USE [master]
GO
CREATE LOGIN [OrphansApp] WITH PASSWORD=N'OrphansApp3', DEFAULT_DATABASE=[OrphansDB], CHECK_EXPIRATION=OFF, CHECK_POLICY=ON
GO

USE [OrphansDB]
GO
CREATE USER [OrphansApp] FOR LOGIN [OrphansApp] WITH DEFAULT_SCHEMA=[db_owner]
GO
