//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrphanageV3.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OrphanageV3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap AddPic {
            get {
                object obj = ResourceManager.GetObject("AddPic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die العنوان ähnelt.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die العمر ähnelt.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die و ähnelt.
        /// </summary>
        public static string AndString {
            get {
                return ResourceManager.GetString("AndString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die صورة خلفية ähnelt.
        /// </summary>
        public static string BackPhoto {
            get {
                return ResourceManager.GetString("BackPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die المبلغ ähnelt.
        /// </summary>
        public static string BailAmount {
            get {
                return ResourceManager.GetString("BailAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die كفالة منتهية ähnelt.
        /// </summary>
        public static string BailIsEnded {
            get {
                return ResourceManager.GetString("BailIsEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die كفالة عائلية ähnelt.
        /// </summary>
        public static string BailIsFamily {
            get {
                return ResourceManager.GetString("BailIsFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die كفالة شهرية ähnelt.
        /// </summary>
        public static string BailIsMonthly {
            get {
                return ResourceManager.GetString("BailIsMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BailPic {
            get {
                object obj = ResourceManager.GetObject("BailPic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die بيانات اساسية ähnelt.
        /// </summary>
        public static string BasicData {
            get {
                return ResourceManager.GetString("BasicData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die صورة شهادة الولادة ähnelt.
        /// </summary>
        public static string BirthCertificatePhoto {
            get {
                return ResourceManager.GetString("BirthCertificatePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die تاريخ الميلاد ähnelt.
        /// </summary>
        public static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die مكان الولادة ähnelt.
        /// </summary>
        public static string BirthPlace {
            get {
                return ResourceManager.GetString("BirthPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die صورة كاملة ähnelt.
        /// </summary>
        public static string BodyPhoto {
            get {
                return ResourceManager.GetString("BodyPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die لا ähnelt.
        /// </summary>
        public static string BooleanFalse {
            get {
                return ResourceManager.GetString("BooleanFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die نعم ähnelt.
        /// </summary>
        public static string BooleanTrue {
            get {
                return ResourceManager.GetString("BooleanTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die عدد الأخوة ähnelt.
        /// </summary>
        public static string BrothersCountString {
            get {
                return ResourceManager.GetString("BrothersCountString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die الغاء ähnelt.
        /// </summary>
        public static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die اسم أب المعيل ähnelt.
        /// </summary>
        public static string CaregiverFatherName {
            get {
                return ResourceManager.GetString("CaregiverFatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die اسم المعيل ähnelt.
        /// </summary>
        public static string CaregiverFirstName {
            get {
                return ResourceManager.GetString("CaregiverFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die اسم المعيل الكامل ähnelt.
        /// </summary>
        public static string CaregiverFullName {
            get {
                return ResourceManager.GetString("CaregiverFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die رقم المعيل ähnelt.
        /// </summary>
        public static string CaregiverID {
            get {
                return ResourceManager.GetString("CaregiverID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die رقم هوية المعيل ähnelt.
        /// </summary>
        public static string CaregiverIdentityNumber {
            get {
                return ResourceManager.GetString("CaregiverIdentityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die كنية المعيل ähnelt.
        /// </summary>
        public static string CaregiverLastName {
            get {
                return ResourceManager.GetString("CaregiverLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die المعيلين ähnelt.
        /// </summary>
        public static string Caregivers {
            get {
                return ResourceManager.GetString("Caregivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die رقم الجوال ähnelt.
        /// </summary>
        public static string CellPhone {
            get {
                return ResourceManager.GetString("CellPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die سم ähnelt.
        /// </summary>
        public static string Centimeter {
            get {
                return ResourceManager.GetString("Centimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die تغير المعيل ähnelt.
        /// </summary>
        public static string ChangeCaregiverText {
            get {
                return ResourceManager.GetString("ChangeCaregiverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ChildrenPic {
            get {
                object obj = ResourceManager.GetObject("ChildrenPic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die المدينة ähnelt.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die رقم القيد ähnelt.
        /// </summary>
        public static string CivilRegisterNumber {
            get {
                return ResourceManager.GetString("CivilRegisterNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die اللون ähnelt.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ColorPickerPic {
            get {
                object obj = ResourceManager.GetObject("ColorPickerPic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die الأعمدة ähnelt.
        /// </summary>
        public static string Columns {
            get {
                return ResourceManager.GetString("Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ColumnsPic {
            get {
                object obj = ResourceManager.GetObject("ColumnsPic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die الصلة بالمعيل ähnelt.
        /// </summary>
        public static string ConsanguinityToCaregiver {
            get {
                return ResourceManager.GetString("ConsanguinityToCaregiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die الكلفة ähnelt.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die يوماً ähnelt.
        /// </summary>
        public static string DaysAccusativeString {
            get {
                return ResourceManager.GetString("DaysAccusativeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die أيام ähnelt.
        /// </summary>
        public static string DaysString {
            get {
                return ResourceManager.GetString("DaysString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die يوم ähnelt.
        /// </summary>
        public static string DayString {
            get {
                return ResourceManager.GetString("DayString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DeletePic {
            get {
                object obj = ResourceManager.GetObject("DeletePic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die حذف ähnelt.
        /// </summary>
        public static string Detele {
            get {
                return ResourceManager.GetString("Detele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die اسحب الأعمدة من و إلى الشبكة ähnelt.
        /// </summary>
        public static string DragAndDropColumnHere {
            get {
                return ResourceManager.GetString("DragAndDropColumnHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die تعديل ähnelt.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap EditPic {
            get {
                object obj = ResourceManager.GetObject("EditPic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die معدل الدرجات ähnelt.
        /// </summary>
        public static string EducationAvaregeGrade {
            get {
                return ResourceManager.GetString("EducationAvaregeGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die شهادة دراسية ähnelt.
        /// </summary>
        public static string EducationCertificateImage1 {
            get {
                return ResourceManager.GetString("EducationCertificateImage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die شهادة دراسية ähnelt.
        /// </summary>
        public static string EducationCertificateImage2 {
            get {
                return ResourceManager.GetString("EducationCertificateImage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die بيانات دراسية ähnelt.
        /// </summary>
        public static string EducationData {
            get {
                return ResourceManager.GetString("EducationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die الكلفة الشهرية ähnelt.
        /// </summary>
        public static string EducationMonthlyCost {
            get {
                return ResourceManager.GetString("EducationMonthlyCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die اسباب التخلف عن الدراسة ähnelt.
        /// </summary>
        public static string EducationNonStudyingReasons {
            get {
                return ResourceManager.GetString("EducationNonStudyingReasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die متخلف ähnelt.
        /// </summary>
        public static string EducationNonStudyKeyword {
            get {
                return ResourceManager.GetString("EducationNonStudyKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die أدخل سبب التخلف عن الدراسة ähnelt.
        /// </summary>
        public static string EducationReasonNullText {
            get {
                return ResourceManager.GetString("EducationReasonNullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die اسم المدرسة ähnelt.
        /// </summary>
        public static string EducationSchoolName {
            get {
                return ResourceManager.GetString("EducationSchoolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die أدخل اسم المدرسة ähnelt.
        /// </summary>
        public static string EducationSchoolNameNullText {
            get {
                return ResourceManager.GetString("EducationSchoolNameNullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die المرحلة الدراسية ähnelt.
        /// </summary>
        public static string EducationStage {
            get {
                return ResourceManager.GetString("EducationStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die متخلف عن الدراسة ähnelt.
        /// </summary>
        public static string EducationStageDefaultString {
            get {
                return ResourceManager.GetString("EducationStageDefaultString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die أدخل المرحلة الدراسية ähnelt.
        /// </summary>
        public static string EducationStageNullString {
            get {
                return ResourceManager.GetString("EducationStageNullString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die الأيميل ähnelt.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die لايمكن حذف السجل ähnelt.
        /// </summary>
        public static string ErrorMessageCannotDelete {
            get {
                return ResourceManager.GetString("ErrorMessageCannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die استبعاد ähnelt.
        /// </summary>
        public static string Exclude {
            get {
                return ResourceManager.GetString("Exclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die فيسبوك ähnelt.
        /// </summary>
        public static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die صورة الوجه ähnelt.
        /// </summary>
        public static string FacePhoto {
            get {
                return ResourceManager.GetString("FacePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die صورة دفتر العائلة ähnelt.
        /// </summary>
        public static string FamilyCardPhoto {
            get {
                return ResourceManager.GetString("FamilyCardPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die علامة لونية للعائلة ähnelt.
        /// </summary>
        public static string FamilyColor {
            get {
                return ResourceManager.GetString("FamilyColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die رقم العائلة ähnelt.
        /// </summary>
        public static string FamilyID {
            get {
                return ResourceManager.GetString("FamilyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die العائلة مستبعدة ähnelt.
        /// </summary>
        public static string FamilyIsExcluded {
            get {
                return ResourceManager.GetString("FamilyIsExcluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die عمر الأب ähnelt.
        /// </summary>
        public static string FatherAge {
            get {
                return ResourceManager.GetString("FatherAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die تاريخ ميلاد الأب ähnelt.
        /// </summary>
        public static string FatherBirthday {
            get {
                return ResourceManager.GetString("FatherBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die تاريخ وفاة الأب ähnelt.
        /// </summary>
        public static string FatherDeathDate {
            get {
                return ResourceManager.GetString("FatherDeathDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die اسم الجد ähnelt.
        /// </summary>
        public static string FatherFatherName {
            get {
                return ResourceManager.GetString("FatherFatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die اسم الاب الكامل ähnelt.
        /// </summary>
        public static string FatherFullName {
            get {
                return ResourceManager.GetString("FatherFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die رقم الأب ähnelt.
        /// </summary>
        public static string FatherID {
            get {
                return ResourceManager.GetString("FatherID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die رقم هوية الأب ähnelt.
        /// </summary>
        public static string FatherIdentityNumber {
            get {
                return ResourceManager.GetString("FatherIdentityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die كنية الأب ähnelt.
        /// </summary>
        public static string FatherLastName {
            get {
                return ResourceManager.GetString("FatherLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die اسم الأب ähnelt.
        /// </summary>
        public static string FatherName {
            get {
                return ResourceManager.GetString("FatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Father Name ähnelt.
        /// </summary>
        public static string FatherNameE {
            get {
                return ResourceManager.GetString("FatherNameE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FatherPic {
            get {
                object obj = ResourceManager.GetObject("FatherPic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die رقم الفاكس ähnelt.
        /// </summary>
        public static string FaxNumber {
            get {
                return ResourceManager.GetString("FaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die الإناث ähnelt.
        /// </summary>
        public static string FemalesString {
            get {
                return ResourceManager.GetString("FemalesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die انثى ähnelt.
        /// </summary>
        public static string FemaleString {
            get {
                return ResourceManager.GetString("FemaleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die الاسم الأول ähnelt.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die First Name ähnelt.
        /// </summary>
        public static string FirstNameE {
            get {
                return ResourceManager.GetString("FirstNameE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die قياس القدم ähnelt.
        /// </summary>
        public static string FootSize {
            get {
                return ResourceManager.GetString("FootSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die صورة أمامية ähnelt.
        /// </summary>
        public static string FrontPhoto {
            get {
                return ResourceManager.GetString("FrontPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die الاسم الكامل ähnelt.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die الجنس ähnelt.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die اسحب الاعمدة هنا ähnelt.
        /// </summary>
        public static string GirdViewGroupPanelElementText {
            get {
                return ResourceManager.GetString("GirdViewGroupPanelElementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die اسم الجد ähnelt.
        /// </summary>
        public static string GrandFatherName {
            get {
                return ResourceManager.GetString("GrandFatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die تجميع بواسطة : ähnelt.
        /// </summary>
        public static string GridViewGroupByText {
            get {
                return ResourceManager.GetString("GridViewGroupByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die رقم الكفيل ähnelt.
        /// </summary>
        public static string GuarantorID {
            get {
                return ResourceManager.GetString("GuarantorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die اسم الكفيل ähnelt.
        /// </summary>
        public static string GuarantorName {
            get {
                return ResourceManager.GetString("GuarantorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die بيانات طبية ähnelt.
        /// </summary>
        public static string HealthData {
            get {
                return ResourceManager.GetString("HealthData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die الطبيب المشرف ähnelt.
        /// </summary>
        public static string HealthDoctor {
            get {
                return ResourceManager.GetString("HealthDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die أدخل اسم الطبيب المشرف ähnelt.
        /// </summary>
        public static string HealthDoctorNullText {
            get {
                return ResourceManager.GetString("HealthDoctorNullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die الأدوية ähnelt.
        /// </summary>
        public static string HealthMedicen {
            get {
                return ResourceManager.GetString("HealthMedicen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die المرض أسم أدخل ähnelt.
        /// </summary>
        public static string HealthMedicenNullText {
            get {
                return ResourceManager.GetString("HealthMedicenNullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die صورة التقرير الطبي ähnelt.
        /// </summary>
        public static string HealthReportFilePhoto {
            get {
                return ResourceManager.GetString("HealthReportFilePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die اسم المرض ähnelt.
        /// </summary>
        public static string HealthSicknessName {
            get {
                return ResourceManager.GetString("HealthSicknessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die المرض أسم أدخل ähnelt.
        /// </summary>
        public static string HealthSicknessNameNullText {
            get {
                return ResourceManager.GetString("HealthSicknessNameNullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap HidePic {
            get {
                object obj = ResourceManager.GetObject("HidePic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die هاتف المنزل ähnelt.
        /// </summary>
        public static string HomePhone {
            get {
                return ResourceManager.GetString("HomePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die الرقم ähnelt.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die رقم الهوية ähnelt.
        /// </summary>
        public static string IdentityCardNumber {
            get {
                return ResourceManager.GetString("IdentityCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die الدخل ähnelt.
        /// </summary>
        public static string Income {
            get {
                return ResourceManager.GetString("Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die الإنترنت ähnelt.
        /// </summary>
        public static string Internet {
            get {
                return ResourceManager.GetString("Internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die مكفول ähnelt.
        /// </summary>
        public static string IsBailed {
            get {
                return ResourceManager.GetString("IsBailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die مستبعد ähnelt.
        /// </summary>
        public static string IsExcluded {
            get {
                return ResourceManager.GetString("IsExcluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die مريض ähnelt.
        /// </summary>
        public static string IsSick {
            get {
                return ResourceManager.GetString("IsSick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die يدرس ähnelt.
        /// </summary>
        public static string IsStudying {
            get {
                return ResourceManager.GetString("IsStudying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die العمل ähnelt.
        /// </summary>
        public static string Jop {
            get {
                return ResourceManager.GetString("Jop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die كغ ähnelt.
        /// </summary>
        public static string Kilogramm {
            get {
                return ResourceManager.GetString("Kilogramm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die الكنية ähnelt.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last Name ähnelt.
        /// </summary>
        public static string LastNameE {
            get {
                return ResourceManager.GetString("LastNameE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die أقل من يوم ähnelt.
        /// </summary>
        public static string LessThanDayString {
            get {
                return ResourceManager.GetString("LessThanDayString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die أقل من شهر ähnelt.
        /// </summary>
        public static string LessThanMonthString {
            get {
                return ResourceManager.GetString("LessThanMonthString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die اقل من سنة ähnelt.
        /// </summary>
        public static string LessThanYearString {
            get {
                return ResourceManager.GetString("LessThanYearString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap loading {
            get {
                object obj = ResourceManager.GetObject("loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die الذكور ähnelt.
        /// </summary>
        public static string MalesString {
            get {
                return ResourceManager.GetString("MalesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ذكر ähnelt.
        /// </summary>
        public static string MaleString {
            get {
                return ResourceManager.GetString("MaleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die رقم الجوال ähnelt.
        /// </summary>
        public static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die شهراً ähnelt.
        /// </summary>
        public static string MonthesAccusativeString {
            get {
                return ResourceManager.GetString("MonthesAccusativeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die أشهر ähnelt.
        /// </summary>
        public static string MonthesString {
            get {
                return ResourceManager.GetString("MonthesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die شهر ähnelt.
        /// </summary>
        public static string MonthString {
            get {
                return ResourceManager.GetString("MonthString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die عمر الأم ähnelt.
        /// </summary>
        public static string MotherAge {
            get {
                return ResourceManager.GetString("MotherAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die تاريخ ميلاد الأم ähnelt.
        /// </summary>
        public static string MotherBirthday {
            get {
                return ResourceManager.GetString("MotherBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die تاريخ وفاة الأم ähnelt.
        /// </summary>
        public static string MotherDeathDate {
            get {
                return ResourceManager.GetString("MotherDeathDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die اسم اب الأم ähnelt.
        /// </summary>
        public static string MotherFatherName {
            get {
                return ResourceManager.GetString("MotherFatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die اسم الأم ähnelt.
        /// </summary>
        public static string MotherFirstName {
            get {
                return ResourceManager.GetString("MotherFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die اسم الأم الكامل ähnelt.
        /// </summary>
        public static string MotherFullName {
            get {
                return ResourceManager.GetString("MotherFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die اسم زوج الأم ähnelt.
        /// </summary>
        public static string MotherHusbandName {
            get {
                return ResourceManager.GetString("MotherHusbandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die رقم الأم ähnelt.
        /// </summary>
        public static string MotherID {
            get {
                return ResourceManager.GetString("MotherID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die رقم هوية الأم ähnelt.
        /// </summary>
        public static string MotherIdentityNumber {
            get {
                return ResourceManager.GetString("MotherIdentityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die الأم متوفية ähnelt.
        /// </summary>
        public static string MotherIsDead {
            get {
                return ResourceManager.GetString("MotherIsDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die الأم متزوجة ähnelt.
        /// </summary>
        public static string MotherIsMarried {
            get {
                return ResourceManager.GetString("MotherIsMarried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die كنية الأم ähnelt.
        /// </summary>
        public static string MotherLastName {
            get {
                return ResourceManager.GetString("MotherLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MotherPic {
            get {
                object obj = ResourceManager.GetObject("MotherPic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die الاسم ähnelt.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ملاحظات ähnelt.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die من ähnelt.
        /// </summary>
        public static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die عمر اليتيم ähnelt.
        /// </summary>
        public static string OrphanAge {
            get {
                return ResourceManager.GetString("OrphanAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die تاريخ الميلاد اليتيم ähnelt.
        /// </summary>
        public static string OrphanBirthday {
            get {
                return ResourceManager.GetString("OrphanBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die مكان ولادة اليتيم ähnelt.
        /// </summary>
        public static string OrphanBirthplace {
            get {
                return ResourceManager.GetString("OrphanBirthplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die علامة لونية لليتيم ähnelt.
        /// </summary>
        public static string OrphanColor {
            get {
                return ResourceManager.GetString("OrphanColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die صلة اليتيم بالمعيل ähnelt.
        /// </summary>
        public static string OrphanConsanguinityToCaregiver {
            get {
                return ResourceManager.GetString("OrphanConsanguinityToCaregiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die خاله ähnelt.
        /// </summary>
        public static string OrphanConsanguinityToCaregiverSimple1 {
            get {
                return ResourceManager.GetString("OrphanConsanguinityToCaregiverSimple1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die امها ähnelt.
        /// </summary>
        public static string OrphanConsanguinityToCaregiverSimple10 {
            get {
                return ResourceManager.GetString("OrphanConsanguinityToCaregiverSimple10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die عمته ähnelt.
        /// </summary>
        public static string OrphanConsanguinityToCaregiverSimple11 {
            get {
                return ResourceManager.GetString("OrphanConsanguinityToCaregiverSimple11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die عمتها ähnelt.
        /// </summary>
        public static string OrphanConsanguinityToCaregiverSimple12 {
            get {
                return ResourceManager.GetString("OrphanConsanguinityToCaregiverSimple12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die خالته ähnelt.
        /// </summary>
        public static string OrphanConsanguinityToCaregiverSimple13 {
            get {
                return ResourceManager.GetString("OrphanConsanguinityToCaregiverSimple13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die خالتها ähnelt.
        /// </summary>
        public static string OrphanConsanguinityToCaregiverSimple14 {
            get {
                return ResourceManager.GetString("OrphanConsanguinityToCaregiverSimple14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die لايوجد صلة قرابة ähnelt.
        /// </summary>
        public static string OrphanConsanguinityToCaregiverSimple15 {
            get {
                return ResourceManager.GetString("OrphanConsanguinityToCaregiverSimple15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die قريبه ähnelt.
        /// </summary>
        public static string OrphanConsanguinityToCaregiverSimple16 {
            get {
                return ResourceManager.GetString("OrphanConsanguinityToCaregiverSimple16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die قريبته ähnelt.
        /// </summary>
        public static string OrphanConsanguinityToCaregiverSimple17 {
            get {
                return ResourceManager.GetString("OrphanConsanguinityToCaregiverSimple17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die خالها ähnelt.
        /// </summary>
        public static string OrphanConsanguinityToCaregiverSimple2 {
            get {
                return ResourceManager.GetString("OrphanConsanguinityToCaregiverSimple2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die عمه ähnelt.
        /// </summary>
        public static string OrphanConsanguinityToCaregiverSimple3 {
            get {
                return ResourceManager.GetString("OrphanConsanguinityToCaregiverSimple3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die عمها ähnelt.
        /// </summary>
        public static string OrphanConsanguinityToCaregiverSimple4 {
            get {
                return ResourceManager.GetString("OrphanConsanguinityToCaregiverSimple4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die جده ähnelt.
        /// </summary>
        public static string OrphanConsanguinityToCaregiverSimple5 {
            get {
                return ResourceManager.GetString("OrphanConsanguinityToCaregiverSimple5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die جدها ähnelt.
        /// </summary>
        public static string OrphanConsanguinityToCaregiverSimple6 {
            get {
                return ResourceManager.GetString("OrphanConsanguinityToCaregiverSimple6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die جدته ähnelt.
        /// </summary>
        public static string OrphanConsanguinityToCaregiverSimple7 {
            get {
                return ResourceManager.GetString("OrphanConsanguinityToCaregiverSimple7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die جدتها ähnelt.
        /// </summary>
        public static string OrphanConsanguinityToCaregiverSimple8 {
            get {
                return ResourceManager.GetString("OrphanConsanguinityToCaregiverSimple8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die امه ähnelt.
        /// </summary>
        public static string OrphanConsanguinityToCaregiverSimple9 {
            get {
                return ResourceManager.GetString("OrphanConsanguinityToCaregiverSimple9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die يتيم ähnelt.
        /// </summary>
        public static string OrphanEditViewTitle {
            get {
                return ResourceManager.GetString("OrphanEditViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die اسم اليتيم ähnelt.
        /// </summary>
        public static string OrphanFirstName {
            get {
                return ResourceManager.GetString("OrphanFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die جنس اليتيم ähnelt.
        /// </summary>
        public static string OrphanGender {
            get {
                return ResourceManager.GetString("OrphanGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die رقم اليتيم ähnelt.
        /// </summary>
        public static string OrphanID {
            get {
                return ResourceManager.GetString("OrphanID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die رقم هوية اليتيم ähnelt.
        /// </summary>
        public static string OrphanIdentityNumber {
            get {
                return ResourceManager.GetString("OrphanIdentityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die رقم هوية اليتيم ähnelt.
        /// </summary>
        public static string OrphanIDNumber {
            get {
                return ResourceManager.GetString("OrphanIDNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die اليتم مكفول ähnelt.
        /// </summary>
        public static string OrphanIsBailed {
            get {
                return ResourceManager.GetString("OrphanIsBailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die اليتيم مستبعد ähnelt.
        /// </summary>
        public static string OrphanIsExcluded {
            get {
                return ResourceManager.GetString("OrphanIsExcluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die اليتيم مريض ähnelt.
        /// </summary>
        public static string OrphanIsSick {
            get {
                return ResourceManager.GetString("OrphanIsSick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die كنية اليتيم ähnelt.
        /// </summary>
        public static string OrphanLastName {
            get {
                return ResourceManager.GetString("OrphanLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die عدد الايتام ähnelt.
        /// </summary>
        public static string OrphansCount {
            get {
                return ResourceManager.GetString("OrphansCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die قصة اليتيم ähnelt.
        /// </summary>
        public static string OrphanStory {
            get {
                return ResourceManager.GetString("OrphanStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die طول اليتيم ähnelt.
        /// </summary>
        public static string OrphanTallness {
            get {
                return ResourceManager.GetString("OrphanTallness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ايتام ähnelt.
        /// </summary>
        public static string OrphanViewTitle {
            get {
                return ResourceManager.GetString("OrphanViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die وزن اليتيم ähnelt.
        /// </summary>
        public static string OrphanWeight {
            get {
                return ResourceManager.GetString("OrphanWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die بينات أخرى ähnelt.
        /// </summary>
        public static string OtherData {
            get {
                return ResourceManager.GetString("OtherData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die صفحة ähnelt.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ParentsPic {
            get {
                object obj = ResourceManager.GetObject("ParentsPic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ارقام الهواتف ähnelt.
        /// </summary>
        public static string PhoneNumbers {
            get {
                return ResourceManager.GetString("PhoneNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die صورة ähnelt.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap preload {
            get {
                object obj = ResourceManager.GetObject("preload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die السبب ähnelt.
        /// </summary>
        public static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RefreshPic {
            get {
                object obj = ResourceManager.GetObject("RefreshPic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die تاريخ التسجيل ähnelt.
        /// </summary>
        public static string RegDate {
            get {
                return ResourceManager.GetString("RegDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die حفظ ähnelt.
        /// </summary>
        public static string SaveText {
            get {
                return ResourceManager.GetString("SaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die تحديد ähnelt.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die عرض الكفالات ähnelt.
        /// </summary>
        public static string ShowBails {
            get {
                return ResourceManager.GetString("ShowBails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die عرض المعيلين ähnelt.
        /// </summary>
        public static string ShowCaregivers {
            get {
                return ResourceManager.GetString("ShowCaregivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die عرض العائلات ähnelt.
        /// </summary>
        public static string ShowFamilies {
            get {
                return ResourceManager.GetString("ShowFamilies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die عرض الأباء ähnelt.
        /// </summary>
        public static string ShowFathers {
            get {
                return ResourceManager.GetString("ShowFathers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die عرض الكفلاء ähnelt.
        /// </summary>
        public static string ShowGuarantors {
            get {
                return ResourceManager.GetString("ShowGuarantors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die عرض الأمهات ähnelt.
        /// </summary>
        public static string ShowMothers {
            get {
                return ResourceManager.GetString("ShowMothers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die عرض الأيتام ähnelt.
        /// </summary>
        public static string ShowOrphans {
            get {
                return ResourceManager.GetString("ShowOrphans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SiblingsPic {
            get {
                object obj = ResourceManager.GetObject("SiblingsPic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die المحافظة ähnelt.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die القصة ähnelt.
        /// </summary>
        public static string Story {
            get {
                return ResourceManager.GetString("Story", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die الشارع ähnelt.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die الطول ähnelt.
        /// </summary>
        public static string Tallness {
            get {
                return ResourceManager.GetString("Tallness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die يومان ähnelt.
        /// </summary>
        public static string TowDaysString {
            get {
                return ResourceManager.GetString("TowDaysString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die شهران ähnelt.
        /// </summary>
        public static string TowMonthesString {
            get {
                return ResourceManager.GetString("TowMonthesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die البلدة ähnelt.
        /// </summary>
        public static string Town {
            get {
                return ResourceManager.GetString("Town", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die سنتين ähnelt.
        /// </summary>
        public static string TowYearsString {
            get {
                return ResourceManager.GetString("TowYearsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die تويتر ähnelt.
        /// </summary>
        public static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die الغاء الاستبعاد ähnelt.
        /// </summary>
        public static string UnExclude {
            get {
                return ResourceManager.GetString("UnExclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap UnhidePic {
            get {
                object obj = ResourceManager.GetObject("UnhidePic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap UnknownBoyPic {
            get {
                object obj = ResourceManager.GetObject("UnknownBoyPic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap UnknownGirlPic {
            get {
                object obj = ResourceManager.GetObject("UnknownGirlPic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap UnknownPic {
            get {
                object obj = ResourceManager.GetObject("UnknownPic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die اسم المستخدم ähnelt.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die الوزن ähnelt.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die هاتف العمل ähnelt.
        /// </summary>
        public static string WorkPhone {
            get {
                return ResourceManager.GetString("WorkPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die سنوات ähnelt.
        /// </summary>
        public static string YearsString {
            get {
                return ResourceManager.GetString("YearsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die سنة ähnelt.
        /// </summary>
        public static string YearString {
            get {
                return ResourceManager.GetString("YearString", resourceCulture);
            }
        }
    }
}
