//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrphanageV3.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OrphanageV3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die العمر ähnelt.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die تاريخ الميلاد ähnelt.
        /// </summary>
        public static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die مكان الولادة ähnelt.
        /// </summary>
        public static string BirthPlace {
            get {
                return ResourceManager.GetString("BirthPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die اسم أب المعيل ähnelt.
        /// </summary>
        public static string CaregiverFatherName {
            get {
                return ResourceManager.GetString("CaregiverFatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die اسم المعيل ähnelt.
        /// </summary>
        public static string CaregiverFirstName {
            get {
                return ResourceManager.GetString("CaregiverFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die رقم المعيل ähnelt.
        /// </summary>
        public static string CaregiverID {
            get {
                return ResourceManager.GetString("CaregiverID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die رقم هوية المعيل ähnelt.
        /// </summary>
        public static string CaregiverIdentityNumber {
            get {
                return ResourceManager.GetString("CaregiverIdentityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die كنية المعيل ähnelt.
        /// </summary>
        public static string CaregiverLastName {
            get {
                return ResourceManager.GetString("CaregiverLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die اللون ähnelt.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die الصلة بالمعيل ähnelt.
        /// </summary>
        public static string ConsanguinityToCaregiver {
            get {
                return ResourceManager.GetString("ConsanguinityToCaregiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die مستبعد ähnelt.
        /// </summary>
        public static string Excluded {
            get {
                return ResourceManager.GetString("Excluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die علامة لونية للعائلة ähnelt.
        /// </summary>
        public static string FamilyColor {
            get {
                return ResourceManager.GetString("FamilyColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die رقم العائلة ähnelt.
        /// </summary>
        public static string FamilyID {
            get {
                return ResourceManager.GetString("FamilyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die العائلة مستبعدة ähnelt.
        /// </summary>
        public static string FamilyIsExcluded {
            get {
                return ResourceManager.GetString("FamilyIsExcluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die عمر الأب ähnelt.
        /// </summary>
        public static string FatherAge {
            get {
                return ResourceManager.GetString("FatherAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die تاريخ ميلاد الأب ähnelt.
        /// </summary>
        public static string FatherBirthday {
            get {
                return ResourceManager.GetString("FatherBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die تاريخ وفاة الأب ähnelt.
        /// </summary>
        public static string FatherDeathDate {
            get {
                return ResourceManager.GetString("FatherDeathDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die رقم الأب ähnelt.
        /// </summary>
        public static string FatherID {
            get {
                return ResourceManager.GetString("FatherID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die رقم هوية الأب ähnelt.
        /// </summary>
        public static string FatherIdentityNumber {
            get {
                return ResourceManager.GetString("FatherIdentityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die كنية الأب ähnelt.
        /// </summary>
        public static string FatherLastName {
            get {
                return ResourceManager.GetString("FatherLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die اسم الأب ähnelt.
        /// </summary>
        public static string FatherName {
            get {
                return ResourceManager.GetString("FatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die الاسم الأول ähnelt.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die قياس القدم ähnelt.
        /// </summary>
        public static string FootSize {
            get {
                return ResourceManager.GetString("FootSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die الجنس ähnelt.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die اسحب الاعمدة هنا ähnelt.
        /// </summary>
        public static string GirdViewGroupPanelElementText {
            get {
                return ResourceManager.GetString("GirdViewGroupPanelElementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die اسم الجد ähnelt.
        /// </summary>
        public static string GrandFatherName {
            get {
                return ResourceManager.GetString("GrandFatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die تجميع بواسطة : ähnelt.
        /// </summary>
        public static string GridViewGroupByText {
            get {
                return ResourceManager.GetString("GridViewGroupByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die رقم الكفيل ähnelt.
        /// </summary>
        public static string GuarantorID {
            get {
                return ResourceManager.GetString("GuarantorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die الرقم ähnelt.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die رقم الهوية ähnelt.
        /// </summary>
        public static string IdentityNumber {
            get {
                return ResourceManager.GetString("IdentityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die مكفول ähnelt.
        /// </summary>
        public static string IsBailed {
            get {
                return ResourceManager.GetString("IsBailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die مستبعد ähnelt.
        /// </summary>
        public static string IsExcluded {
            get {
                return ResourceManager.GetString("IsExcluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die مريض ähnelt.
        /// </summary>
        public static string IsSick {
            get {
                return ResourceManager.GetString("IsSick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die الكنية ähnelt.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die عمر الأم ähnelt.
        /// </summary>
        public static string MotherAge {
            get {
                return ResourceManager.GetString("MotherAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die تاريخ ميلاد الأم ähnelt.
        /// </summary>
        public static string MotherBirthday {
            get {
                return ResourceManager.GetString("MotherBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die تاريخ وفاة الأم ähnelt.
        /// </summary>
        public static string MotherDeathDate {
            get {
                return ResourceManager.GetString("MotherDeathDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die رقم الأم ähnelt.
        /// </summary>
        public static string MotherID {
            get {
                return ResourceManager.GetString("MotherID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die رقم هوية الأم ähnelt.
        /// </summary>
        public static string MotherIdentityNumber {
            get {
                return ResourceManager.GetString("MotherIdentityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die كنية الأم ähnelt.
        /// </summary>
        public static string MotherLastName {
            get {
                return ResourceManager.GetString("MotherLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die اسم الأم ähnelt.
        /// </summary>
        public static string MotherName {
            get {
                return ResourceManager.GetString("MotherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die من ähnelt.
        /// </summary>
        public static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die عمر اليتيم ähnelt.
        /// </summary>
        public static string OrphanAge {
            get {
                return ResourceManager.GetString("OrphanAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die تاريخ الميلاد اليتيم ähnelt.
        /// </summary>
        public static string OrphanBirthday {
            get {
                return ResourceManager.GetString("OrphanBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die مكان ولادة اليتيم ähnelt.
        /// </summary>
        public static string OrphanBirthplace {
            get {
                return ResourceManager.GetString("OrphanBirthplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die علامة لونية لليتيم ähnelt.
        /// </summary>
        public static string OrphanColor {
            get {
                return ResourceManager.GetString("OrphanColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die صلة اليتيم بالمعيل ähnelt.
        /// </summary>
        public static string OrphanConsanguinityToCaregiver {
            get {
                return ResourceManager.GetString("OrphanConsanguinityToCaregiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die اسم اليتيم ähnelt.
        /// </summary>
        public static string OrphanFirstName {
            get {
                return ResourceManager.GetString("OrphanFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die جنس اليتيم ähnelt.
        /// </summary>
        public static string OrphanGender {
            get {
                return ResourceManager.GetString("OrphanGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die رقم اليتيم ähnelt.
        /// </summary>
        public static string OrphanID {
            get {
                return ResourceManager.GetString("OrphanID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die رقم هوية اليتيم ähnelt.
        /// </summary>
        public static string OrphanIdentityNumber {
            get {
                return ResourceManager.GetString("OrphanIdentityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die رقم هوية اليتيم ähnelt.
        /// </summary>
        public static string OrphanIDNumber {
            get {
                return ResourceManager.GetString("OrphanIDNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die اليتم مكفول ähnelt.
        /// </summary>
        public static string OrphanIsBailed {
            get {
                return ResourceManager.GetString("OrphanIsBailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die اليتيم مستبعد ähnelt.
        /// </summary>
        public static string OrphanIsExcluded {
            get {
                return ResourceManager.GetString("OrphanIsExcluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die اليتيم مريض ähnelt.
        /// </summary>
        public static string OrphanIsSick {
            get {
                return ResourceManager.GetString("OrphanIsSick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die كنية اليتيم ähnelt.
        /// </summary>
        public static string OrphanLastName {
            get {
                return ResourceManager.GetString("OrphanLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die قصة اليتيم ähnelt.
        /// </summary>
        public static string OrphanStory {
            get {
                return ResourceManager.GetString("OrphanStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die طول اليتيم ähnelt.
        /// </summary>
        public static string OrphanTallness {
            get {
                return ResourceManager.GetString("OrphanTallness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ايتام ähnelt.
        /// </summary>
        public static string OrphanViewTitle {
            get {
                return ResourceManager.GetString("OrphanViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die وزن اليتيم ähnelt.
        /// </summary>
        public static string OrphanWeight {
            get {
                return ResourceManager.GetString("OrphanWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die صفحة ähnelt.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die تاريخ التسجيل ähnelt.
        /// </summary>
        public static string RegisterDate {
            get {
                return ResourceManager.GetString("RegisterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die اسباب التخلف عن الدراسة ähnelt.
        /// </summary>
        public static string StudyReasons {
            get {
                return ResourceManager.GetString("StudyReasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die المرحلة الدراسية ähnelt.
        /// </summary>
        public static string StudyStage {
            get {
                return ResourceManager.GetString("StudyStage", resourceCulture);
            }
        }
    }
}
