//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrphanageV3.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yyyy/MM/dd")]
        public string GeneralDateFormat {
            get {
                return ((string)(this["GeneralDateFormat"]));
            }
            set {
                this["GeneralDateFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseBackgroundColor {
            get {
                return ((bool)(this["UseBackgroundColor"]));
            }
            set {
                this["UseBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowHiddenRows {
            get {
                return ((bool)(this["ShowHiddenRows"]));
            }
            set {
                this["ShowHiddenRows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseFatherName {
            get {
                return ((bool)(this["UseFatherName"]));
            }
            set {
                this["UseFatherName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-")]
        public char AddressSeparator {
            get {
                return ((char)(this["AddressSeparator"]));
            }
            set {
                this["AddressSeparator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Orphan.layout")]
        public string OrphanLayoutFilePath {
            get {
                return ((string)(this["OrphanLayoutFilePath"]));
            }
            set {
                this["OrphanLayoutFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:1515/")]
        public string OrphanageServiceURL {
            get {
                return ((string)(this["OrphanageServiceURL"]));
            }
            set {
                this["OrphanageServiceURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int DefaultPageSize {
            get {
                return ((int)(this["DefaultPageSize"]));
            }
            set {
                this["DefaultPageSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Caregiver.layout")]
        public string CaregiverLayoutFilePath {
            get {
                return ((string)(this["CaregiverLayoutFilePath"]));
            }
            set {
                this["CaregiverLayoutFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mother.layout")]
        public string MotherLayoutFilePath {
            get {
                return ((string)(this["MotherLayoutFilePath"]));
            }
            set {
                this["MotherLayoutFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Father.layout")]
        public string FatherLayoutFilePath {
            get {
                return ((string)(this["FatherLayoutFilePath"]));
            }
            set {
                this["FatherLayoutFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Family.layout")]
        public string FamiliesLayoutFilePath {
            get {
                return ((string)(this["FamiliesLayoutFilePath"]));
            }
            set {
                this["FamiliesLayoutFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bail.layout")]
        public string BailsLayoutFilePath {
            get {
                return ((string)(this["BailsLayoutFilePath"]));
            }
            set {
                this["BailsLayoutFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseColors {
            get {
                return ((bool)(this["UseColors"]));
            }
            set {
                this["UseColors"] = value;
            }
        }
    }
}
